config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :todo_lists do
    resources :todo_items
  end
  namespace :todo_list do
    resources :todo_items
  end
   
  root to: "home#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo_item.rb
class TodoItem < ApplicationRecord
  belongs_to :todo_list

  scope :completed, -> do
    where(completed: true)
  end
end

app/models/todo_list.rb
class TodoList < ApplicationRecord
  has_many :todo_items
  belongs_to :user

  scope :filter_by_id, -> (user_id) { where user_id: user_id }

  def percent_complete
    return 0 if total_items == 0
    ( 100 * completed_items.to_f / total_items).round(1)
  end

  def completed_items
    @completed_items ||= todo_items.completed.count
  end 

  def total_items
    @total_items ||= todo_items.count
  end

  def status
    case percent_complete.to_i
    when 0 
       'Not started'
    when 100 
       'Completed'
    else
      'In Progress'
    end
  end

  def badge_color
    case percent_complete.to_i
    when 0 
     'danger'
    when 100 
     'info'
    else
      'success'
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :todo_lists
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
    end
end

app/controllers/todo_items_controller.rb
class TodoItemsController < ApplicationController
  before_action :set_todo_list
  before_action :set_todo_item, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!


  # GET todo_lists/1/todo_items
  def index
    @todo_items = @todo_list.todo_items
  end

  # GET todo_lists/1/todo_items/1
  def show
  end

  # GET todo_lists/1/todo_items/new
  def new
    @todo_item = @todo_list.todo_items.build
  end

  # GET todo_lists/1/todo_items/1/edit
  def edit
  end

  # POST todo_lists/1/todo_items
  def create
    @todo_item = @todo_list.todo_items.build(todo_item_params)

    if @todo_item.save
      redirect_to(@todo_item.todo_list)
    else
      render action: 'new'
    end
  end

  # PUT todo_lists/1/todo_items/1
  def update
    if @todo_item.update(todo_item_params)
      redirect_to([@todo_item.todo_list, @todo_item], notice: 'Todo item was successfully updated.')
    else
      render action: 'edit'
    end
  end

  # DELETE todo_lists/1/todo_items/1
  def destroy
    @todo_item.destroy

    redirect_to todo_list_todo_items_url(@todo_list)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo_list
      @todo_list = TodoList.find(params[:todo_list_id])
    end

    def set_todo_item
      @todo_item = @todo_list.todo_items.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def todo_item_params
      params.require(:todo_item).permit(:task, :completed, :completed_at, :todo_list_id)
    end
end

app/controllers/todo_lists_controller.rb
class TodoListsController < ApplicationController
  before_action :set_todo_list, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  # GET /todo_lists or /todo_lists.json
  def index
    @todo_lists = TodoList.filter_by_id(current_user.id)
  end

  # GET /todo_lists/1 or /todo_lists/1.json
  def show
    @todo_item = TodoItem.new
  end

  # GET /todo_lists/new
  def new
    @todo_list = TodoList.new
  end

  # GET /todo_lists/1/edit
  def edit
  end

  # POST /todo_lists or /todo_lists.json
  def create
    @todo_list = TodoList.new(todo_list_params)

    respond_to do |format|
      if @todo_list.save
        format.html { redirect_to @todo_list, notice: "Todo list was successfully created." }
        format.json { render :show, status: :created, location: @todo_list }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todo_lists/1 or /todo_lists/1.json
  def update
    respond_to do |format|
      if @todo_list.update(todo_list_params)
        format.html { redirect_to @todo_list, notice: "Todo list was successfully updated." }
        format.json { render :show, status: :ok, location: @todo_list }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todo_lists/1 or /todo_lists/1.json
  def destroy
    @todo_list.destroy
    respond_to do |format|
      format.html { redirect_to todo_lists_url, notice: "Todo list was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo_list
      @todo_list = TodoList.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def todo_list_params
      params.require(:todo_list).permit(:title, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/todo_items_helper.rb
module TodoItemsHelper
end

app/helpers/todo_lists_helper.rb
module TodoListsHelper
end

app/views/home/index.html.erb
  <div class="card-body d-flex flex-column align-items-center">
    <h1 class="card-title py-5">WELCOME</h1>
    <h3 class="card-subtitle text-secondary pb-0">JOIN US TO START YOUR LISTS</h3>
    <% if !user_signed_in? %><small class="pb-5 pt-0 text-muted">( or just want to see the app? log in with try@try , password: 123456 )</small><% end %>
    <div class="d-flex pb-5">
        </div>
        </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ToDo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/e2d86b63b2.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="bg-light">
<%= render partial: 'shared/navbar' %>

         <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
<div class="container mt-5">
  <div class="row ">
  <div class="col">
<div class="card text-center">
      <%= yield %>
</div>
  </div>
</div>
  </div>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark text-white bg-dark">
  <div class="container-fluid">
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
        <%= link_to "Home", root_path, class:"nav-link active fs-5" %>
      </ul>


      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
      <% if user_signed_in? %>
      <li class="nav-item">
      <%= link_to "My Lists",  todo_lists_path, class:"nav-link active fs-5" %>
      </li>
      <li class="nav-item">
      <%= link_to "Logout",  destroy_user_session_path, method: :delete, class:"nav-link active fs-5" %>
      </li>

      <% else %>
      <li class="nav-item">
      <%= link_to "Sign Up",  new_user_registration_path, class:"nav-link active fs-5" %>
      </li>
      <li class="nav-item">
      <%= link_to "Login",  new_user_session_path, class:"nav-link active fs-5" %>
      </li>
      <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/todo_lists/_form.html.erb
<%= form_with(model: todo_list) do |form| %>
  <% if todo_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(todo_list.errors.count, "error") %> prohibited this todo_list from being saved:</h2>

      <ul>
        <% todo_list.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field py-2">
    <%= form.label :title, class:"fs-5" %>
    <%= form.text_field :title %>
  </div>

    <div class="field">
    <%= form.number_field :user_id, id: :todo_list_user_id, class:"form-control", value: current_user.id, type: :hidden  %>
  </div>

  <div class="actions py-3">
    <%= form.submit class:"btn btn-success btn-md" %>
  </div>
<% end %>

app/views/todo_lists/edit.html.erb
<h2 class="py-4">Edit Your List's Name</h2>

<%= render 'form', todo_list: @todo_list %>

  <div class="position-absolute top-0 start-0">
<%= link_to todo_lists_path, class:"btn btn-lg" do %>
<i class="fas fa-caret-square-left fa-3x"></i>
<% end %></div>

app/views/todo_lists/index.html.erb
<div class="card-header d-flex justify-content-between py-4">
  <h1 class="m-0 text-dark"> Todo Lists</h1>
  <%= link_to 'New Todo List', new_todo_list_path, class:"btn btn-primary btn-lg my-auto" %>
</div>


<div class="card-body">
<ul class="list-group">
  <% @todo_lists.each do |todo_list| %>
  <%= link_to todo_list, class:"text-decoration-none" do %>
    <li class="list-group-item d-flex justify-content-between pb-2 pt-3">
      <div>
        <h5 class="m-0 text-dark text-start text-capitalize pb-1">
          <b><%= todo_list.title %></b>
          <span class="badge rounded-pill bg-<%= todo_list.badge_color %>"><%= todo_list.status %></span>
        </h5>
        <p class="text-secondary m-0"> <%= todo_list.percent_complete %>% Completed ( <%= todo_list.completed_items %>/<%= todo_list.total_items %> Todo Items ) </p>
      </div>
      <div>
      <%= link_to '#', class:"btn btn-danger btn-lg", data: { reflex: 'click->TodoList#delete_that_list', id: todo_list.id } do %>
      <i class="fas fa-trash-alt"></i>
      <% end %>
        <%= link_to 'Edit', edit_todo_list_path(todo_list), class:'btn btn-secondary btn-lg' %>
      </div>
    </li>
    <% end %>
  <% end %>
</ul>
</div>

app/views/todo_lists/new.html.erb
<h2 class="py-4">New Todo List</h2>

<%= render 'form', todo_list: @todo_list %>

  <div class="position-absolute top-0 start-0">
<%= link_to todo_lists_path, class:"btn btn-lg" do %>
<i class="fas fa-caret-square-left fa-3x"></i>
<% end %></div>

app/views/todo_lists/show.html.erb
<div class="card-header d-flex justify-content-between">
  <div class="py-1">
    <h4 class="m-0 text-start text-capitalize">
      <b><%= @todo_list.title %></b>
      <span class="badge bg-<%= @todo_list.badge_color %>"><%= @todo_list.status %></span>
    </h4>
    <p class="text-secondary m-0"> <%= @todo_list.percent_complete %>% Completed ( <%= @todo_list.completed_items %>/<%= @todo_list.total_items %> Todo Items ) </p>
  </div>
  <div class="py-1">
    <%= link_to 'Back to List Menu', todo_lists_path, class:'btn btn-secondary btn-lg' %>
  </div>
</div>
<div class="card-body">
  <div class="progress mb-3">
    <div class="progress-bar" role="progressbar" style="width:<%= @todo_list.percent_complete %>%" aria-valuenow="<%= @todo_list.percent_complete %>" aria-valuemin="0" aria-valuemax="100"></div>
  </div>
  <%= form_for([@todo_list, @todo_item]) do |f| %>
    <div class="input-group mb-4">
      <%= f.text_field :task, class:"form-control", placeholder:"Add a new todo item" %>
      <div class="input-group-append">
        <%= f.submit "Add", class:"btn btn-primary input-group-btn" %>
      </div>
    </div>
  <% end %>
  <ul class="list-group">
    <% @todo_list.todo_items.each do |todo_item| %>
      <% if todo_item.completed? %>
        <li class="list-group-item">
          <div class="d-flex justify-content-between">
            <div>
            <span class="text-success text-capitalize text-decoration-line-through fs-5 ">
              <%= todo_item.task %>
            </span>
            </div>
            <div>
            <%= link_to '#', class:"btn btn-danger", data: { reflex: 'click->TodoItem#delete_that_item', id: todo_item.id } do %>
              <i class="fas fa-trash-alt"></i>
            <% end %>
            <%= link_to '#', class:"btn btn-dark", data: { reflex: 'click->TodoItem#complete_negative', id: todo_item.id } do %>
              <i class="fas fa-undo"></i>
            <% end %>
          </div>
          </div>
        </li>
      <% else %>
        <li class="list-group-item">
          <div class="d-flex justify-content-between">
          <div>
            <span class="text-capitalize fs-5 fw-bold">
              <%= todo_item.task %>
            </span>
            </div>
            <div>
            <%= link_to '#', class:"btn btn-danger", data: { reflex: 'click->TodoItem#delete_that_item', id: todo_item.id } do %>
              <i class="fas fa-trash-alt"></i>
            <% end %>
            <%= link_to '#', class:"btn btn-success", data: { reflex: 'click->TodoItem#complete_positive', id: todo_item.id } do %>
              <i class="fas fa-check"></i>
            <% end %>
            </div>
          </div>
        </li>
      <% end %>
    <% end %>
  </ul>
</div>